//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class crn_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crn_detail()
        {
            this.crn_session_timetable = new HashSet<crn_session_timetable>();
            this.student_grade = new HashSet<student_grade>();
        }
    
        public string CRN { get; set; }
        public string TafeCompCode { get; set; }
        public int TermCodeStart { get; set; }
        public int TermYearStart { get; set; }
        public int TermCodeEnd { get; set; }
        public int TermYearEnd { get; set; }
        public string SubjectCode { get; set; }
        public string CampusCode { get; set; }
        public string LecturerID { get; set; }
        public string DepartmentCode { get; set; }
        public System.DateTime FreezeDate { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual campus campus { get; set; }
        public virtual competency competency { get; set; }
        public virtual department department { get; set; }
        public virtual lecturer lecturer { get; set; }
        public virtual subject subject { get; set; }
        public virtual term_datetime term_datetime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crn_session_timetable> crn_session_timetable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_grade> student_grade { get; set; }
    }
}
