//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMAN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_it_studies_devEntities : DbContext
    {
        public admin_it_studies_devEntities()
            : base("name=admin_it_studies_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<campus> campus { get; set; }
        public virtual DbSet<competency> competency { get; set; }
        public virtual DbSet<competency_qualification> competency_qualification { get; set; }
        public virtual DbSet<competency_type> competency_type { get; set; }
        public virtual DbSet<crn_detail> crn_detail { get; set; }
        public virtual DbSet<crn_session_timetable> crn_session_timetable { get; set; }
        public virtual DbSet<day_of_week> day_of_week { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<lecturer> lecturer { get; set; }
        public virtual DbSet<qualification> qualification { get; set; }
        public virtual DbSet<student_grade> student_grade { get; set; }
        public virtual DbSet<student_studyplan> student_studyplan { get; set; }
        public virtual DbSet<studyplan_qualification> studyplan_qualification { get; set; }
        public virtual DbSet<studyplan_subject> studyplan_subject { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<subject_qualification> subject_qualification { get; set; }
        public virtual DbSet<term_datetime> term_datetime { get; set; }
    }
}
