//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_studyplan
    {
        public string StudentID { get; set; }
        public string QualCode { get; set; }
        public int TermCodeStart { get; set; }
        public int TermYearStart { get; set; }
        public string EnrolmentType { get; set; }
    
        public virtual qualification qualification { get; set; }
        public virtual term_datetime term_datetime { get; set; }
    }
}
