//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studyplan_qualification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studyplan_qualification()
        {
            this.studyplan_subject = new HashSet<studyplan_subject>();
        }
    
        public string StudyPlanCode { get; set; }
        public string QualCode { get; set; }
        public int Priority { get; set; }
    
        public virtual qualification qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studyplan_subject> studyplan_subject { get; set; }
    }
}
